[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler==3.11.3",
    "beautifulsoup4>=4.15.0",
    "cachetools>=7.1.7",
    "cryptography>=50.0.1",
    "diskcache>=5.6.3",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "lxml>=6.1.2",
    "playwright>=1.62.0",
    "prisma>=0.15.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "tzdata==2026.3",
    "tzlocal==5.4.4",
    "uvicorn>=0.52.1",
]
